
/* Drop Tables */

DROP TABLE IF EXISTS SIS_SEG_SOC_ACCION_CALIDAD;
DROP TABLE IF EXISTS SIS_SEG_SOC_LOG_PQRS;
DROP TABLE IF EXISTS SIS_SEG_SOC_OBSERVACION_PQRS;
DROP TABLE IF EXISTS SIS_SEG_SOC_TAREA;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_ACTIVIDAD;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_ADJUNTO;
DROP TABLE IF EXISTS SIS_SEG_SOC_RECIBO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_CLIENTE;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_CIUDAD;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_COLORIMETRIA;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_PLAZO_RESPUESTA;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_COMPLEJIDAD;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_DEPARTAMENTO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_IMPACTO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_PAIS;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_USUARIO_PROCESO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_PROCESO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_USUARIO_PROYECTO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_PROYECTO;
DROP TABLE IF EXISTS SIS_SEG_SOC_P_USUARIO;




/* Create Tables */

CREATE TABLE SIS_SEG_SOC_ACCION_CALIDAD
(
	CONS_ACCION_CALIDAD int NOT NULL,
	CONS_PQRS int NOT NULL,
	COD_PROCESO varchar(100) NOT NULL,
	TIPO_ACCION varchar(30),
	NOMBRE_DOCUMENTO varchar(250),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_ACCION_CALIDAD)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_LOG_PQRS
(
	CONS_LOG_PQRS serial NOT NULL,
	CONS_PQRS int NOT NULL,
	FECHA_LOG timestamp NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	DESCRIPCION varchar(2000),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_LOG_PQRS)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_OBSERVACION_PQRS
(
	CONS_OBSERVACION serial NOT NULL,
	CONS_PQRS int NOT NULL,
	TIPO_OBSERVACION varchar(30),
	OBSERVACION varchar(2000),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_OBSERVACION)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_ACTIVIDAD
(
	CONS_ACTIVIDAD serial NOT NULL,
	-- Usuario que puede realizar la actividad
	ROL varchar(50) NOT NULL,
	NOMBRE varchar(255) NOT NULL,
	FORMULARIO varchar(250) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_ACTIVIDAD)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_ADJUNTO
(
	CONS_ADJUNTO serial NOT NULL,
	CONS_PQRS int NOT NULL,
	NOMBRE_ARCHIVO varchar(250) NOT NULL,
	RUTA_ARCHIVO varchar(250) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_ADJUNTO)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_CIUDAD
(
	CONS_CIUDAD serial NOT NULL,
	CONS_DEPARTAMENTO int NOT NULL,
	NOMBRE varchar(255) NOT NULL UNIQUE,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_CIUDAD)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_CLIENTE
(
	LOGIN varchar(50) NOT NULL,
	NUMERO_IDENTIFICACION varchar(25) NOT NULL UNIQUE,
	CONS_CIUDAD int NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	PRIMER_APELLIDO varchar(250) NOT NULL,
	EMAIL varchar(100),
	TELEFONO varchar(20),
	CELULAR varchar(20),
	NOMBRE_CONTACTO varchar(100),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (LOGIN)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_COLORIMETRIA
(
	CONS_COLORIMETRIA serial NOT NULL,
	CONS_PLAZO_RESPUESTA int NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	COLOR varchar(20) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_COLORIMETRIA)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_COMPLEJIDAD
(
	CONS_COMPLEJIDADES serial NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	DESCRIPCION varchar(500),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_COMPLEJIDADES)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_DEPARTAMENTO
(
	CONS_DEPARTAMENTO serial NOT NULL,
	CONS_PAIS int NOT NULL,
	NOMBRE varchar(255) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_DEPARTAMENTO)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_IMPACTO
(
	CONS_IMPACTO serial NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	DESCRIPCION varchar(500),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_IMPACTO)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_PAIS
(
	CONS_PAIS serial NOT NULL,
	ISO char(2) NOT NULL UNIQUE,
	NOMBRE varchar(255) NOT NULL UNIQUE,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_PAIS)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_PLAZO_RESPUESTA
(
	CONS_PLAZO_RESPUESTA serial NOT NULL,
	CONS_IMPACTO int NOT NULL,
	CONS_COMPLEJIDADES int NOT NULL,
	PRIMER_NOMBRE varchar(250),
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	HABILES varchar(1) NOT NULL,
	TIEMPO numeric(3,0) NOT NULL,
	UNIDAD_TIEMPO varchar(20) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_PLAZO_RESPUESTA)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_PROCESO
(
	COD_PROCESO varchar(100) NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	DETALLE varchar(2000),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (COD_PROCESO)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_PROYECTO
(
	COD_PROYECTO varchar(100) NOT NULL,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	ESTADO varchar(1) NOT NULL,
	DETALLE varchar(2000),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (COD_PROYECTO)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_USUARIO
(
	NUMERO_IDENTIFICACION varchar(25) NOT NULL UNIQUE,
	LOGIN varchar(50) NOT NULL UNIQUE,
	CONS_USUARIO int NOT NULL UNIQUE,
	TIPO_DOCUMENTO char(2) NOT NULL UNIQUE,
	PRIMER_NOMBRE varchar(250) NOT NULL,
	SEGUNDO_NOMBRE varchar(250),
	PRIMER_APELLIDO varchar(250) NOT NULL,
	SEGUNDO_APELLIDO varchar(250),
	FECHA_DE_NACIMIENTO date NOT NULL,
	-- SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO
	ESTADO varchar(1) NOT NULL,
	SEXO char(2) NOT NULL,
	-- SE DIGITA "C" EN CASO DE SER COTIZANTE Y "B" EN CASO DE SER BENEFICIARIO
	VINCULO_LABORAL char(1) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (NUMERO_IDENTIFICACION)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_USUARIO_PROCESO
(
	COD_PROCESO varchar(100) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	NUMERO_IDENTIFICACION varchar(25) NOT NULL UNIQUE
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_P_USUARIO_PROYECTO
(
	COD_PROYECTO varchar(100) NOT NULL,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	NUMERO_IDENTIFICACION varchar(25) NOT NULL UNIQUE
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_RECIBO
(
	CONS_PQRS serial NOT NULL,
	COD_PROCESO varchar(100),
	CONS_IMPACTO int,
	CONS_COMPLEJIDADES int,
	CLIENTE varchar(50) NOT NULL,
	COD_PROYECTO varchar(100),
	MEDIO_COMUNICACION varchar(50) NOT NULL,
	TIPO_SOLICITUD varchar(50) NOT NULL,
	EMAIL_SOLICITANTE varchar(250),
	TELEFONO_SOLICITANTE varchar(50),
	CONTACTO varchar(250) NOT NULL,
	FECHA_EVENTO varchar(50),
	OTRO varchar(500),
	ESTADO varchar(30),
	TIEMPO_PLAZO numeric(3,0),
	UNIDAD_TIEMPO varchar(15),
	FECHA_CIERRE timestamp,
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	NUMERO_IDENTIFICACION varchar(25) NOT NULL UNIQUE,
	PRIMARY KEY (CONS_PQRS)
) WITHOUT OIDS;


CREATE TABLE SIS_SEG_SOC_TAREA
(
	CONS_TAREA serial NOT NULL,
	CONS_PQRS int NOT NULL,
	CONS_ACTIVIDAD int NOT NULL,
	ESTADO varchar(1) NOT NULL,
	-- Fecha en la cual la persona asignada empieza a trabajar en la pqrs
	FECHA_INICIO varchar(100) NOT NULL,
	-- Fecha en la cual el cliente o el usuario que pueda crear PQRS  da por terminada  la tarea asignada.
	FECHA_COMPLETA varchar(100),
	USUARIO_COMPLETA varchar(100),
	TIPO_TAREA varchar(100),
	FECHA_CREA timestamp NOT NULL,
	USUARIO_CREA varchar(100) NOT NULL,
	FECHA_MODIFICA timestamp,
	USUARIO_MODIFICA varchar(100),
	PRIMARY KEY (CONS_TAREA)
) WITHOUT OIDS;



/* Create Foreign Keys */

ALTER TABLE SIS_SEG_SOC_TAREA
	ADD FOREIGN KEY (CONS_ACTIVIDAD)
	REFERENCES SIS_SEG_SOC_P_ACTIVIDAD (CONS_ACTIVIDAD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_CLIENTE
	ADD FOREIGN KEY (CONS_CIUDAD)
	REFERENCES SIS_SEG_SOC_P_CIUDAD (CONS_CIUDAD)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (CLIENTE)
	REFERENCES SIS_SEG_SOC_P_CLIENTE (LOGIN)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_PLAZO_RESPUESTA
	ADD FOREIGN KEY (CONS_COMPLEJIDADES)
	REFERENCES SIS_SEG_SOC_P_COMPLEJIDAD (CONS_COMPLEJIDADES)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (CONS_COMPLEJIDADES)
	REFERENCES SIS_SEG_SOC_P_COMPLEJIDAD (CONS_COMPLEJIDADES)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_CIUDAD
	ADD FOREIGN KEY (CONS_DEPARTAMENTO)
	REFERENCES SIS_SEG_SOC_P_DEPARTAMENTO (CONS_DEPARTAMENTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_PLAZO_RESPUESTA
	ADD FOREIGN KEY (CONS_IMPACTO)
	REFERENCES SIS_SEG_SOC_P_IMPACTO (CONS_IMPACTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (CONS_IMPACTO)
	REFERENCES SIS_SEG_SOC_P_IMPACTO (CONS_IMPACTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_DEPARTAMENTO
	ADD FOREIGN KEY (CONS_PAIS)
	REFERENCES SIS_SEG_SOC_P_PAIS (CONS_PAIS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_COLORIMETRIA
	ADD FOREIGN KEY (CONS_PLAZO_RESPUESTA)
	REFERENCES SIS_SEG_SOC_P_PLAZO_RESPUESTA (CONS_PLAZO_RESPUESTA)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_ACCION_CALIDAD
	ADD FOREIGN KEY (COD_PROCESO)
	REFERENCES SIS_SEG_SOC_P_PROCESO (COD_PROCESO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_USUARIO_PROCESO
	ADD FOREIGN KEY (COD_PROCESO)
	REFERENCES SIS_SEG_SOC_P_PROCESO (COD_PROCESO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (COD_PROCESO)
	REFERENCES SIS_SEG_SOC_P_PROCESO (COD_PROCESO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_USUARIO_PROYECTO
	ADD FOREIGN KEY (COD_PROYECTO)
	REFERENCES SIS_SEG_SOC_P_PROYECTO (COD_PROYECTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (COD_PROYECTO)
	REFERENCES SIS_SEG_SOC_P_PROYECTO (COD_PROYECTO)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_CLIENTE
	ADD FOREIGN KEY (NUMERO_IDENTIFICACION)
	REFERENCES SIS_SEG_SOC_P_USUARIO (NUMERO_IDENTIFICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_USUARIO_PROCESO
	ADD FOREIGN KEY (NUMERO_IDENTIFICACION)
	REFERENCES SIS_SEG_SOC_P_USUARIO (NUMERO_IDENTIFICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_USUARIO_PROYECTO
	ADD FOREIGN KEY (NUMERO_IDENTIFICACION)
	REFERENCES SIS_SEG_SOC_P_USUARIO (NUMERO_IDENTIFICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_RECIBO
	ADD FOREIGN KEY (NUMERO_IDENTIFICACION)
	REFERENCES SIS_SEG_SOC_P_USUARIO (NUMERO_IDENTIFICACION)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_ACCION_CALIDAD
	ADD FOREIGN KEY (CONS_PQRS)
	REFERENCES SIS_SEG_SOC_RECIBO (CONS_PQRS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_LOG_PQRS
	ADD FOREIGN KEY (CONS_PQRS)
	REFERENCES SIS_SEG_SOC_RECIBO (CONS_PQRS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_OBSERVACION_PQRS
	ADD FOREIGN KEY (CONS_PQRS)
	REFERENCES SIS_SEG_SOC_RECIBO (CONS_PQRS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_P_ADJUNTO
	ADD FOREIGN KEY (CONS_PQRS)
	REFERENCES SIS_SEG_SOC_RECIBO (CONS_PQRS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;


ALTER TABLE SIS_SEG_SOC_TAREA
	ADD FOREIGN KEY (CONS_PQRS)
	REFERENCES SIS_SEG_SOC_RECIBO (CONS_PQRS)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



/* Comments */

COMMENT ON COLUMN SIS_SEG_SOC_LOG_PQRS.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_ACTIVIDAD.ROL IS 'Usuario que puede realizar la actividad';
COMMENT ON COLUMN SIS_SEG_SOC_P_COLORIMETRIA.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_COMPLEJIDAD.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_IMPACTO.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_PLAZO_RESPUESTA.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_PROCESO.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_USUARIO.ESTADO IS 'SE DEFINE "A" PARA ACTIVO,"I" PARA INACTIVO';
COMMENT ON COLUMN SIS_SEG_SOC_P_USUARIO.VINCULO_LABORAL IS 'SE DIGITA "C" EN CASO DE SER COTIZANTE Y "B" EN CASO DE SER BENEFICIARIO';
COMMENT ON COLUMN SIS_SEG_SOC_TAREA.FECHA_INICIO IS 'Fecha en la cual la persona asignada empieza a trabajar en la pqrs';
COMMENT ON COLUMN SIS_SEG_SOC_TAREA.FECHA_COMPLETA IS 'Fecha en la cual el cliente o el usuario que pueda crear PQRS  da por terminada  la tarea asignada.';



